name: terraform-apply

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply-hub:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: stacks/hub

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"

      - name: Azure Login (OIDC - branch based)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=backend.hcl

      - name: Terraform Apply (Hub)
        run: terraform apply -auto-approve

  apply-spokes:
    runs-on: ubuntu-latest
    needs: apply-hub
    strategy:
      fail-fast: false
      matrix:
        stack: [ spoke-dev, spoke-uat, spoke-prd ]

    defaults:
      run:
        shell: bash
        working-directory: stacks/${{ matrix.stack }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"

      - name: Azure Login (OIDC - branch based)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=backend.hcl

      - name: Terraform Apply (${{ matrix.stack }})
        run: terraform apply -auto-approve
# trigger

