name: terraform-apply
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply-hub:
    runs-on: ubuntu-latest
    environment: hub
    defaults:
      run:
        shell: bash
        working-directory: stacks/hub
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"
      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - run: terraform init -reconfigure -backend-config=backend.hcl
      - run: terraform apply -auto-approve

  apply-spokes:
    runs-on: ubuntu-latest
    needs: apply-hub
    strategy:
      fail-fast: false
      matrix:
        stack: [spoke-dev, spoke-uat, spoke-prd]
    environment: ${{ matrix.stack }}
    defaults:
      run:
        shell: bash
        working-directory: stacks/${{ matrix.stack }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"
      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - run: terraform init -reconfigure -backend-config=backend.hcl
      - run: terraform apply -auto-approve
